language: generic
sudo: required
services: 
    - docker
before_install:
    - docker build -t erikaleigh/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true erikaleigh/react-test npm test

after_success:
    - docker build -t erikaleigh/multi-client ./client
    - docker build -t erikaleigh/multi-nginx ./nginx
    - docker build -t erikaleigh/multi-server ./server
    - docker build -t erikaleigh/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push erikaleigh/multi-client
    - docker push erikaleigh/multi-nginx
    - docker push erikaleigh/multi-server
    - docker push erikaleigh/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-467766844762
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY